export { default as StrukturTable } from './struktur';
export { default as CreateStruktur } from './struktur/create';
export { default as UpdateStruktur } from './struktur/update';
export { default as AgendaTable } from './agenda';
export { default as CreateAgenda } from './agenda/create';
export { default as UpdateAgenda } from './agenda/update';
export { default as BeritaTable } from './berita'
export { default as CreateBerita } from './berita/create'
export { default as UpdateBerita } from './berita/update'
export { default as LembagaTable } from './lembaga'
export { default as CreateLembaga } from './lembaga/create'
export { default as UpdateLembaga } from './lembaga/update'
export { default as WisataTable } from './wisata'
export { default as CreateWisata } from './wisata/create'
export { default as UpdateWisata } from './wisata/update'
export { default as LapakTable } from './lapak'
export { default as CreateLapak } from './lapak/create'
export { default as UpdateLapak } from './lapak/update'
export { default as PrestasiTable } from './prestasi'
export { default as CreatePrestasi } from './prestasi/create'
export { default as UpdatePrestasi } from './prestasi/update'
export { default as PembangunanTable } from './pembangunan'
export { default as CreatePembangunan } from './pembangunan/create'
export { default as UpdatePembangunan } from './pembangunan/update'
export { default as WilayahTable } from './wilayah'
export { default as CreateWilayah } from './wilayah/create'
export { default as UpdateWilayah } from './wilayah/update'
export { default as DanaDesaTable } from './dana-desa'
export { default as CreateDanaDesa } from './dana-desa/create'
export { default as UpdateDanaDesa } from './dana-desa/update'
export { default as GalleryPhoto } from './photo'
export { default as GalleryVideo } from './videos'
